- name: Update and Upgrade debian
  hosts: deb-bast
  tasks:

  - name: upgrade all packages 
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
 
  - name: install apt-transport-https
    apt:
      name: apt-transport-https
      state: latest

  - name: install ca-certificates
    apt:
      name: ca-certificates
      state: latest

  - name: install gnupg-agent
    apt:
      name: gnupg-agent
      state: latest
      
  - name: install software-properties-common
    apt:
      name: software-properties-common
      state: latest
      
  - name: install vim
    apt:
      name: vim
      state: latest
  
  - name: install ssh
    apt:
      name: ssh
      state: latest

  - name: install gpg
    apt:
      name: gpg
      state: latest

  - name: install tar
    apt:
      name: tar
      state: latest

  - name: install rsync
    apt:
      name: rsync
      state: latest

  - name: install tcpdump
    apt:
      name: tcpdump
      state: latest

  - name: install python3
    apt:
      name: python3
      state: latest

  - name: install netcat
    apt:
      name: netcat
      state: latest

  - name: install curl
    apt:
      name: curl
      state: latest

  - name: install openssl
    apt:
      name: openssl
      state: latest

  - name: install ufw
    apt:
      name: ufw
      state: latest
      
  - name: install fail2ban
    apt:
      name: fail2ban
      state: latest
      
  - name: install ansible
    apt:
      name: ansible
      state: latest
      
  - name: install git
    apt:
      name: git
      state: latest
      
  - name: install tmux
    apt:
      name: tmux
      state: latest
      
  - name: set ufw to allow https
    shell: ufw allow https
    args:
      executable: /bin/bash
      
  - name: set ufw to allow ssh
    shell: ufw allow ssh
    args:
      executable: /bin/bash

  - name: set ufw to allow syslog
    shell: ufw allow syslog
    args:
      executable: /bin/bash
      
  - name: set ufw to reload
    shell: ufw reload
    args:
      executable: /bin/bash
      
  - name: set ufw to enable
    shell: echo "y" | ufw enable
    args:
      executable: /bin/bash
      
  - name: set fail2ban
    shell: systemctl enable fail2ban
    args:
      executable: /bin/bash
      
  - name: restart fail2ban
    shell: systemctl restart fail2ban
    args:
      executable: /bin/bash

  - name: remove old docker packages to make room for the right ones
    apt:
      name: docker docker-engine docker.io containerd runc
      state: absent
      
  - name: add docker repo key
    shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    args:
      executable: /bin/bash      
   
  - name: add docker repo 
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    args:
      executable: /bin/bash    

  - name: upgrade all packages again and autoclean
    apt:
      upgrade: yes
      update_cache: yes
      autoclean: yes
      cache_valid_time: 86400

  - name: install docker-ce
    apt:
      name: docker-ce
      state: latest
      
  - name: install docker-ce-cli
    apt:
      name: docker-ce-cli
      state: latest
      
  - name: install containerd.io
    apt:
      name: containerd.io
      state: latest      

  - name: install snapd
    apt:
      name: snapd
      state: latest 
      
  - name: add microk8s snap
    shell: snap install microk8s --classic
    args:
      executable: /bin/bash       
