---

- name: Update and Upgrade debian
  hosts: deb-bast
  tasks:

  - name: upgrade all packages 
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  
  - name: install docker-ce
    apt:
      name: docker-ce
      state: latest
      
  - name: install docker-ce-cli
    apt:
      name: docker-ce-cli
      state: latest
      
  - name: install containerd.io
    apt:
      name: containerd.io
      state: latest      

  - name: install snapd
    apt:
      name: snapd
      state: latest 
      
  - name: add microk8s snap
    shell: snap install microk8s --classic   

  - name: stop microk8s for now
    shell: microk8s stop

...
